#ifndef CONST_H
#define CONST_H
#define MAX_LENGTH  1024*2
//头部总长度
#define HEAD_TOTAL_LEN 4
//头部id长度
#define HEAD_ID_LEN 2
//头部数据长度
#define HEAD_DATA_LEN 2
#define MAX_RECVQUE  10000
#define MAX_SENDQUE 1000

enum MSG_IDS {
	MSG_HELLO_WORD = 1001,
	MSG_REGISTER,
	MSG_LOGIN,
	MSG_LOGOUT,
	MSG_ADD_FRIEND,
	MSG_CREATE_GROUP,
	MSG_JOIN_GROUP,
	MSG_ONE_CHAT,
	MSG_GROUP_CHAT,
};

#endif // CONST_H